version: '2'
services:
    portainer-ce:
        ports:
            - '9443:9443/tcp'
            - '9000:9000/tcp'
            - '8000:8000/tcp'
        environment:
            - TZ=Europe/Oslo
        container_name: portainer
        restart: unless-stopped
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/data/portainer:/data'
            - '/etc/localtime:/etc/localtime:ro'
        image: 'portainer/portainer-ce:latest'

    home-assistant:
        container_name: homeassistant
        privileged: true
        restart: unless-stopped
        environment:
            - TZ=Europe/Oslo
        volumes:
            - '/data/homeassistant:/config'
        network_mode: host
        image: 'ghcr.io/home-assistant/home-assistant:stable'
        depends_on:
            - mosquitto

    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto
        restart: unless-stopped
        ports:
            - "1883:1883/tcp"
        environment:
            - TZ=Europe/Oslo
        volumes:
            - '/data/mosquitto/config:/mosquitto/config'
            - '/data/mosquitto/data:/mosquitto/data'
            - '/data/mosquitto/log:/mosquitto/log'
        stdin_open: true
        tty: true
