version: '3.8'
services:
    portainer-ce:
        ports:
          - '9443:9443/tcp'
          - '9000:9000/tcp'
          - '8000:8000/tcp'
        environment:
          - TZ=Europe/Oslo
        container_name: portainer
        restart: unless-stopped
        hostname: portainer
        volumes:
          - '/var/run/docker.sock:/var/run/docker.sock'
          - '/data/portainer:/data'
          - '/etc/localtime:/etc/localtime:ro'
        image: 'portainer/portainer-ce:latest'
        labels:
          - "com.centurylinklabs.watchtower.monitor-only=true"
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3         

    home-assistant:
        container_name: homeassistant
        privileged: true
        restart: unless-stopped
        hostname: home-assistant 
        environment:
          - TZ=Europe/Oslo
        volumes:
          - '/data/homeassistant:/config'
        network_mode: host
        image: 'ghcr.io/home-assistant/home-assistant:stable'
        depends_on:
          - mosquitto
        labels:
          - "com.centurylinklabs.watchtower.monitor-only=true"
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3

    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto
        restart: unless-stopped
        hostname: mosquitto
        ports:
          - "1883:1883/tcp"
        environment:
          - TZ=Europe/Oslo
        volumes:
          - '/data/mosquitto/config:/mosquitto/config'
          - '/data/mosquitto/data:/mosquitto/data'
          - '/data/mosquitto/log:/mosquitto/log'
        stdin_open: true
        tty: true
        depends_on:
          - zigbee2mqtt
        labels:
          - "com.centurylinklabs.watchtower.monitor-only=true"
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3

    zigbee2mqtt:
        container_name: zigbee2mqtt
        image: koenkk/zigbee2mqtt
        restart: unless-stopped
        hostname: zigbee2mqtt 
        ports:
          - "8099:8099/tcp"
        environment:
          - TZ=Europe/Oslo
        volumes:
          - /data/zigbee2mqtt/data:/app/data
          - /run/udev:/run/udev:ro
        devices:
          - /dev/ttyUSB0:/dev/ttyACM0
            #          - /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0:/dev/ttyACM0
        labels:
          - "com.centurylinklabs.watchtower.monitor-only=true"
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3

    watchtower:
        container_name: watchtower
        image: containrrr/watchtower
        restart: unless-stopped
        hostname: watchtower
        ports:
          - "8080:8080/tcp"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /etc/localtime:/etc/localtime:ro
        environment:
          - TZ=Europe/Oslo
        env_file:
          - notification.env
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3

    myuplink:
        container_name: myuplink
        image: myuplinksmartconnect
        restart: unless-stopped
        hostname: myuplink
        environment:
            - TZ=Europe/Oslo
            - IsInsideDocker=1
            - CheckRemoteStatsIntervalInMinutes=1
            - WaterHeaterMaxPowerInHours=5
            - WaterHeaterMediumPowerInHours=8
            - MediumPowerTargetTemperature=50
            - HighPowerTargetTemperature=75
            - ChangeSchedule=true
            - PowerZone=NO5
            - EnergiBasedCostSaving=false
            - EnergiBasedPeakTimes=weekday6,weekend8
            - MQTTServer=192.168.1.12
            - MQTTServerPort=1883
#Remove comment from below line for extended logging
            - LogLevel=Debug
        env_file:
            - hoiax.env
        labels:
            - "com.centurylinklabs.watchtower.enable=false"
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3

