version: '3.8'

name: python

services:
    portainer-ce:
        ports:
            - '9000:9000'
            - '9443:9443'
            - '8000:8000'
        environment:
            - 'TZ=Europe/Oslo'
        container_name: portainer
        restart: unless-stopped
        hostname: portainer
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/data/portainer:/data'
            - '/etc/localtime:/etc/localtime:ro'
        image: 'portainer/portainer-ce:latest'
        networks:
            default:
                ipv4_address: 10.10.0.10
        labels: 
            - "com.centurylinklabs.watchtower.monitor-only=true"
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3  

    kapacitor:
        container_name: kapacitor
        restart: unless-stopped
        hostname: kapacitor
        ports:
            - '9092:9092'
        volumes:
            - '/data/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro'
            - '/data/kapacitor/lib:/var/lib/kapacitor'
        environment:
            - 'KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086'
            - 'TZ=Europe/Oslo'
        image: kapacitor
        networks:
            default:
                ipv4_address: 10.10.0.8
        labels: 
            - "com.centurylinklabs.watchtower.monitor-only=true"
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3
        depends_on:
            - influxdb
            - chronograf

    chronograf:
        command:
            - '--influxdb-url=http://influxdb:8086'
        container_name: chronograf
        restart: unless-stopped
        hostname: chronograf
        ports:
            - '8888:8888'
        volumes:
            - '/data/chronograf:/var/lib/chronograf'
        environment:
            - 'TZ=Europe/Oslo'
        image: chronograf
        networks:
            default:
                ipv4_address: 10.10.0.7
        labels: 
            - "com.centurylinklabs.watchtower.monitor-only=true"
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3
        depends_on:
            - influxdb

    node-red:
        container_name: mynodered
        restart: unless-stopped
        hostname: nodered
        ports:
            - '1880:1880'
        volumes:
            - '/data/nodered:/data'
            - '/data/powerprice:/powerprice'
        environment:
            - 'TZ=Europe/Oslo'
 #           - 'NODE_RED_ENABLE_PROJECTS=true'
        image: nodered/node-red
        networks:
            default:
                ipv4_address: 10.10.0.6
        labels: 
            - "com.centurylinklabs.watchtower.monitor-only=true"
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3
        depends_on:
            - influxdb

    grafana:
        container_name: grafana
        restart: unless-stopped
        hostname: grafana
        ports:
            - '3000:3000'
        volumes:
            - '/data/grafana:/var/lib/grafana'
            - '/data/loki/grafana/provisioning/:/etc/grafana/provisioning/'
        environment:
            - 'TZ=Europe/Oslo'
        image: grafana/grafana
        networks:
            default:
                ipv4_address: 10.10.0.5
        labels: 
            - "com.centurylinklabs.watchtower.monitor-only=true"
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3
        depends_on:
            - influxdb

    loki:
        container_name: loki
        restart: unless-stopped
        hostname: loki
        ports:
            - '3100'
        volumes:
            - '/data/loki:/loki'
            - '/data/loki/config:/etc/loki'
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
        command: -config.file=/etc/loki/local-config.yaml
        environment:
            - 'TZ=Europe/Oslo'
        image: grafana/loki
        networks:
            default:
                ipv4_address: 10.10.0.12
        labels: 
            - "com.centurylinklabs.watchtower.monitor-only=true"
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3

    promtail:
        container_name: promtail
        restart: unless-stopped
        hostname: promtail
        ports:
            - '9080:9080'
        volumes:
            - /data/loki/promtail-config.yaml:/etc/promtail/config.yml
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
            - /var/log:/opt/var/log:ro
        environment:
            - 'TZ=Europe/Oslo'
        image: grafana/promtail
        networks:
            default:
                ipv4_address: 10.10.0.13
        labels: 
            - "com.centurylinklabs.watchtower.monitor-only=true"
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3
        depends_on:
            - loki

    influxdb:
        container_name: influxdb
        ports:
            - '8086:8086'
        restart: unless-stopped
        hostname: influxdb
        volumes:
            - '/data/influxdb:/var/lib/influxdb'
            - '/data/influxdb_backup:/opt'
        environment:
            - 'TZ=Europe/Oslo'
        image: 'influxdb:1.8'
        networks:
            default:
                ipv4_address: 10.10.0.3
        labels: 
            - "com.centurylinklabs.watchtower.monitor-only=true"
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3

 #   telegraf:
 #       container_name: telegraf
 #       restart: 'no'
 #       volumes:
 #           - '/data/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf'
 #       environment:
 #           - 'TZ=Europe/Oslo'
 #       image: telegraf
 #       networks:
 #           default:
 #               ipv4_address: 10.10.0.2
 #       labels: 
 #           - "com.centurylinklabs.watchtower.monitor-only=true"

    duplicati:
        container_name: duplicati
        image: duplicati/duplicati
        restart: unless-stopped
        hostname: duplicati
        ports:
            - '8200:8200/tcp'
        environment:
            - 'TZ=TZ=Europe/Oslo'
        volumes:
            - '/data/duplicati/data:/data'
            - '/data:/source:ro'
            - '/home/pi:/hpi:ro'
        networks:
            default:
                ipv4_address: 10.10.0.9
        labels: 
            - "com.centurylinklabs.watchtower.monitor-only=true"
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3

    watchtower:
        container_name: watchtower
        image: containrrr/watchtower
        restart: unless-stopped
        hostname: watchtower
        ports:
             - "8080:8080/tcp"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/localtime:/etc/localtime:ro
        environment:
            - TZ=Europe/Oslo
        env_file:
            - notification.env 
        networks:
            default:
                ipv4_address: 10.10.0.4
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3

    myuplink:
        container_name: myuplink
        image: myuplinksmartconnect
        restart: unless-stopped
        hostname: myuplink
        environment:
            - TZ=Europe/Oslo
            - IsInsideDocker=1
            - CheckRemoteStatsIntervalInMinutes=1
            - WaterHeaterMaxPowerInHours=5
            - WaterHeaterMediumPowerInHours=8
            - MediumPowerTargetTemperature=50
            - HighPowerTargetTemperature=75
            - ChangeSchedule=true
            - PowerZone=NO5
            - EnergiBasedCostSaving=false
            - EnergiBasedPeakTimes=weekday6,weekend8
            - MQTTServer=10.10.0.14
            - MQTTServerPort=1883
#Remove comment from below line for extended logging
            - LogLevel=Debug
        env_file:
            - hoiax.env 
        networks:
            default:
                ipv4_address: 10.10.0.11
        labels: 
            - "com.centurylinklabs.watchtower.enable=false"
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3

    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto
        restart: unless-stopped
        hostname: mosquitto
        ports:
          - "1883:1883/tcp"
        environment:
          - TZ=Europe/Oslo
        volumes:
          - '/data/mosquitto/config:/mosquitto/config'
          - '/data/mosquitto/data:/mosquitto/data'
          - '/data/mosquitto/log:/mosquitto/log'
        stdin_open: true
        tty: true
        networks:
            default:
                ipv4_address: 10.10.0.14
        labels:
          - "com.centurylinklabs.watchtower.monitor-only=true"
        logging:
            driver: json-file
            options:
                max-size: 10m
                max-file: 3

networks:
  default:
    name: influxdb-telegraf-net
    external: true
