name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install lxml
        pip install influxdb
        pip install paho-mqtt
        pip install tinytuya
        pip install beautifulsoup4
        pip install pandas
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --disable=invalid-name,line-too-long --extension-pkg-whitelist=lxml --max-branches=14 $(git ls-files '*.py')
